// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxexpxnknhkgnihnumgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZXhweG5rbmhrZ25paG51bWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTk2MTksImV4cCI6MjA2NTgzNTYxOX0.AoZCVjnQTO1f7waSuj6QnFXzUXiE38oxyHGRIGei1HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);